### ISSUE TITLE
Add link to mpl docs

### ISSUE THREAD

**Issue by tacaswell** [konstantint/matplotlib-venn#18]
Could you please add a link and short description to this page (src https://github.com/matplotlib/matplotlib/blob/master/doc/mpl_toolkits/index.rst renders to http://matplotlib.org/mpl_toolkits/index.html) in the main mpl docs?

**Comment by konstantint** [comment]
OK, I made a [pull request](https://github.com/matplotlib/matplotlib/pull/4505).
