### ISSUE TITLE
How to get correct representation of a perfectly overlapped set of diagrams

### ISSUE THREAD

**Issue by harijay** [konstantint/matplotlib-venn#19]
I have two datasets, one of which is a subset of the other . Does matplotlib-venn plot this type with one of the circles subsumed inside the other. 
In this case , list A has 23 elements and listB has 20 elements all of which are in list A. Is there a way to get a diagram that represents this.
Sorry to submit this as an "issue"

**Comment by konstantint** [comment]
Yes, that situation should work out fine, just specify the appropriate input data.
