### ISSUE TITLE
Venn diagrams don't seem proportional

### ISSUE THREAD

**Issue by wllmtrng** [konstantint/matplotlib-venn#25]
The following venn diagram should be more proportional than it currently is, unless of course this is intended behavior for clarity purposes:

```python
from matplotlib_venn import venn2
venn2(subsets = (100, 0, 99), set_labels = ("People with Cancer", "People with Cancer, and Test Positive"))
```
<img width="520" alt="screen shot 2016-05-01 at 4 15 51 pm" src="https://cloud.githubusercontent.com/assets/1335855/14944929/03e555bc-0fb8-11e6-9ac8-4d8b1a87ea98.png">

**Comment by wllmtrng** [comment]
With values of 100, and 90, it also produces the same diagram.
```
venn2(subsets = (100, 0, 90), set_labels = ("People with Cancer", "People with Cancer, and Test Positive"))
```
<img width="572" alt="screen shot 2016-05-01 at 4 19 34 pm" src="https://cloud.githubusercontent.com/assets/1335855/14944945/ac176978-0fb8-11e6-8091-9b1d6cf64770.png">

**Comment by konstantint** [comment]
The large circle has area 190, the smaller on 90, as intended.
