### ISSUE TITLE
plt is not defined

### ISSUE THREAD

**Issue by tommycarstensen** [konstantint/matplotlib-venn#33]
I get this this error:

    NameError: name 'plt' is not defined

With this code:

    import matplotlib_venn
    matplotlib_venn.venn2((set((1, 2, 3)), set((3, 4, 5))))
    plt.savefig('test.png')

I also tried the given example:

    set1 = set(['A', 'B', 'C', 'D'])
    set2 = set(['B', 'C', 'D', 'E'])
    set3 = set(['C', 'D',' E', 'F', 'G'])

    venn3([set1, set2, set3], ('Set1', 'Set2', 'Set3'))
    plt.show()

**Comment by konstantint** [comment]
There is a commonly implied convention that you do 

`from matplotlib import pyplot as plt`

somewhere in your code.

**Comment by MohammadHeydari** [comment]
> Works fine

**Comment by vidyasastri-421** [comment]
plt.figure(figsize=(8, 6))
# time series plot
sns.tsplot(df_time)
plt.xlabel("Time")
plt.ylabel("Sales")
plt.show()


for this code am getting the error name plt is not defined

**Comment by konstantint** [comment]
Check out my previous comment in this thread.
