### ISSUE TITLE
Feature Request: add ability to set labels to minor regions

### ISSUE THREAD

**Issue by stochastic1** [konstantint/matplotlib-venn#42]
I'd like to be able to put percentage labels on each of the 7 regions in a 3-factor venn plot.
Or names. Or use the percentages as labels within the names.

I'd be willing to help with this. There's a use case in my work.

**Comment by konstantint** [comment]
Check out the `subset_label_formatter` argument of the `venn3` function. Passing something like `lambda x: '%0.2f%%' % (x*100.0/total)` might do what you are looking for.

**Comment by konstantint** [comment]
Duplicate of #8

**Comment by stochastic1** [comment]
That's a great suggestion and it solved what I needed. Thank you!
