### ISSUE TITLE
Embedding matplotlib-venn GUI to Tkinter

### ISSUE THREAD

**Issue by felixlee0530** [konstantint/matplotlib-venn#47]
How can I embed a matplotlib-venn GUI to Tkinter?
I found several resources for embedding standard graphs/charts created with matplotlib, to Tkinter, but not really a case where a matplotlib-venn diagram has been embedded.

**Comment by konstantint** [comment]
A matplotlib-venn plot is just as standard as any other matplotlib chart, so whatever examples you found should work out with Venn diagrams just as well.

**Comment by felixlee0530** [comment]
I tried to follow the official matplotlib guide and it worked partially.
Now the `matplotlib` GUI is not popped out separately in a new window, the Tkinter GUI updates itself to display the `matplotlib` GUI actually. However, it occupies the entire window so I cannot see the Tkinter GUI. How can I make it just to occupy the bottom half of the Tkinter GUI? (It is vertically long, so I would like to use the upper half for my buttons/labels and bottom half for `matplotlib` output)

I also posted this issue in Stackoverflow, so please have a look at the code I posted there.
https://stackoverflow.com/questions/59978383/displaying-embedding-the-matplotlib-diagram-inside-the-tkinter-gui

**Comment by konstantint** [comment]
I don't have experience with TkInter, so I suspect that stackoverflow or the [tkinter-discuss](https://mail.python.org/pipermail/tkinter-discuss/) mailing list is a much better place to seek advice on these questions.
