### ISSUE TITLE
Near-empty (but non-empty!) subset results in no patch being initialised for it.  

### ISSUE THREAD

**Issue by paulbrodersen** [konstantint/matplotlib-venn#49]
Hi Konstantin, 

I had a user raise an [issue](https://github.com/paulbrodersen/matplotlib_venn_wordcloud/issues/6) with my package matplotlib_venn_wordcloud that comes down to matplotlib-venn not producing a patch for a non-empty subset. You do raise a warning (`UserWarning: Bad circle positioning`), so I assume that is a known issue. Do you have any advice on how to work around it?

Best,
Paul

**Comment by konstantint** [comment]
Hi. One way to overcome such a problem manually is to "regularize" the circle positions by increasing the size of the A&B&C region artificially. This nearly always forces the circles closer together in a "nice" configuration, at the cost of less precise relative sizes (but then, they are not precise in such situations anyway).

There's even a utility function `venn3_unweighted` which takes one argument specifying region actual sizes and one argument, specifying the numbers to put on the regions.

As far as automating this issue completely, I'd envision having a customizable layout engine framework with more than one predefined engine, but so far I've never found the time for that.

**Comment by paulbrodersen** [comment]
Thanks for the quick reply. I will play around with `venn3_unweighted`.
