### ISSUE TITLE
Option to set_text_color( 'white') 

### ISSUE THREAD

**Issue by shinokada** [konstantint/matplotlib-venn#52]
I just want to show AND, OR, XOR, etc without any numbers.
Is there a way not showing numbers?

If we can set the text color to white, it won't be shown. 
It will be nice to change text color, font size, etc.

For example, the following shows OR and I want to remove the numbers.

```
%matplotlib inline
from matplotlib_venn import venn2
from matplotlib import pyplot

v = venn2(subsets=(3, 3, 1))
 
v.get_patch_by_id('10').set_color('skyblue')
v.get_patch_by_id('10').set_edgecolor('black')
v.get_patch_by_id('11').set_color('skyblue')
v.get_patch_by_id('11').set_edgecolor('black')
v.get_patch_by_id('01').set_color('skyblue')
v.get_patch_by_id('01').set_edgecolor('black')

pyplot.gca().set_axis_on()
pyplot.gca().set_facecolor('white')
pyplot.show()
```

![image](https://user-images.githubusercontent.com/147320/88596490-2c039b00-d0a0-11ea-8d95-d6960ac225cf.png)

**Comment by konstantint** [comment]
You can simply remove the contents of the respective text labels, e.g.:

```
v = venn2(subsets=(3, 3, 1))
for area in ['01', '10', '11']:
  txt = v.get_label_by_id(area)
  if txt: txt.set_text('')
```

**Comment by shinokada** [comment]
Thanks for the follow-up.
