### ISSUE TITLE
How to set the Venn-diagram figure height

### ISSUE THREAD

**Issue by shinokada** [konstantint/matplotlib-venn#53]
I tried to change the figure height using different methods suggested [here](https://stackoverflow.com/questions/332289/how-do-you-change-the-size-of-figures-drawn-with-matplotlib), but none of them worked.

As you can see in the image below, I want to add more space under A and B by changing the figure height.

What is the best way to do it?

```
%matplotlib inline
from matplotlib_venn import venn2
from matplotlib import pyplot as plt

v = venn2(subsets=(3, 3, 1))

# remove numbers
for area in ['01', '10', '11']:
  txt = v.get_label_by_id(area)
  if txt: txt.set_text('')
 
v.get_patch_by_id('10').set_color('skyblue')
v.get_patch_by_id('10').set_edgecolor('black')
v.get_patch_by_id('11').set_color('skyblue')
v.get_patch_by_id('11').set_edgecolor('black')
v.get_patch_by_id('01').set_color('skyblue')
v.get_patch_by_id('01').set_edgecolor('black')

plt.gca().set_axis_on()
plt.gca().set_facecolor('white')
plt.title("OR")
plt.show()
```

![image](https://user-images.githubusercontent.com/147320/88600889-43478600-d0aa-11ea-82ce-53352979f4c7.png)

**Comment by konstantint** [comment]
Try this:

```
ymin, ymax = plt.gca().get_ylim()
plt.ylim(ymin - 0.5, ymax)
```

**Comment by shinokada** [comment]
Thanks. It works.
