### ISSUE TITLE
Single circle and label positions

### ISSUE THREAD

**Issue by shinokada** [konstantint/matplotlib-venn#54]
I am trying to create the following diagram with the matplotlib-venn.

![image](https://user-images.githubusercontent.com/147320/88605484-0339d080-d0b5-11ea-8d35-6f8a02dd57f5.png)

I have the following code but as you can see there are some problems.

1. Is it possible to draw a single Venn-diagram?
2. lines are not right.
3. Position of not A: How can I change the position of the label?
4. How can I add U (universal set)?

```
%matplotlib inline
from matplotlib_venn import venn2
from matplotlib import pyplot as plt

v = venn2(subsets=(3, 3, 1), set_labels = ('A', "A'"))

# remove numbers
for area in ['01', '10', '11']:
  txt = v.get_label_by_id(area)
  if txt: txt.set_text('')

# changing colors and edge colors  
v.get_patch_by_id('10').set_color('skyblue')
v.get_patch_by_id('10').set_edgecolor('black')
v.get_patch_by_id('11').set_color('skyblue')
v.get_patch_by_id('11').set_edgecolor('skyblue')
v.get_patch_by_id('01').set_color('white')
v.get_patch_by_id('01').set_edgecolor('white')

# changing background
plt.gca().set_axis_on()
plt.gca().set_facecolor('white')
plt.title("Negation", fontsize=30)
ymin, ymax = plt.gca().get_ylim()
plt.ylim(ymin - 0.1, ymax)
plt.show()
```

![image](https://user-images.githubusercontent.com/147320/88606460-b5729780-d0b7-11ea-85f8-d2fa5bb67946.png)

**Comment by konstantint** [comment]
I don't think you need matlotlib-venn to plot a single circle. Just draw a [circle patch](https://matplotlib.org/api/_as_gen/matplotlib.patches.Circle.html) and a [rectangle patch](https://matplotlib.org/api/_as_gen/matplotlib.patches.Rectangle.html#matplotlib.patches.Rectangle) along with the needed labels.

**Comment by shinokada** [comment]
I got up to this so far.
Only U is missing. 
Any idea how to add U outside the box?

```
import pylab as plt
from matplotlib_venn import venn3, venn3_circles

v = venn3(subsets=(1,1,0,1,0,0,0),set_labels = ('','',''))
# remove numbers
for area in ['01', '10']:
  txt = v.get_label_by_id(area)
  if txt: txt.set_text('')
        
v.get_patch_by_id('100').set_color('white')
v.get_patch_by_id('001').set_color('white')
v.get_label_by_id('010').set_text('A')
v.get_label_by_id('001').set_text("A'")

# changing background
plt.gca().set_axis_on()
plt.gca().set_facecolor('white')
plt.title("Negation", fontsize=30)
plt.show()
```

![image](https://user-images.githubusercontent.com/147320/88611521-2a4bce80-d0c4-11ea-85ad-e28f9b3968a1.png)

**Comment by shinokada** [comment]
I got it.

I added the following.

```
plt.text(-1, 0.2, r'U', fontsize=15)
```

![image](https://user-images.githubusercontent.com/147320/88613012-7fd5aa80-d0c7-11ea-807a-a31c9a0bbefc.png)
