### ISSUE TITLE
How to set the fontsize when you use set_text('A')

### ISSUE THREAD

**Issue by shinokada** [konstantint/matplotlib-venn#56]
What is the best way to set the text size when you use `set_text('A')`.

```
v.get_label_by_id('010').set_text('A')
```

**Comment by konstantint** [comment]
The object returned by `v.get_label_by_id('010')` is an instance of [matplotlib.text.Text](https://matplotlib.org/api/text_api.html#matplotlib.text.Text). You are free to use any of its methods to modify its properties. In your case you should probably look into `set_fontsize`.

**Comment by shinokada** [comment]
Thank you very much for your kind reply.

I appreciate your help.

**Comment by shinokada** [comment]
Hi,

I just wanted to say thank you again. I wrote [an article on Medium](https://towardsdatascience.com/how-to-draw-venn-diagrams-on-jupyter-75c604b093ac) about Matplotlib-venn.
