### ISSUE TITLE
Feature Request: Percentage Labels

### ISSUE THREAD

**Issue by jcharkow** [konstantint/matplotlib-venn#63]
Hi,

I was wondering if there was an easy way to change the subset labels so that they were expressed as a percentage of the total number of points. 

I was looking at trying to do this using the subset_label_formatter but I could not find a way

**Comment by konstantint** [comment]
For example like that:
```
subsets = (1,2,3)
venn2(subsets, subset_label_formatter=lambda v: '{0:0.2%}'.format(v/sum(subsets)))
```
or, if you divide by the sum before the plot:
```
subsets = [v/sum(subsets) for v in subsets]
venn2(subsets, subset_label_formatter='{0:0.2%}'.format)
```

**Comment by jcharkow** [comment]
Thank you for your response and sorry for the delayed reply, this solved my issue!
Just in case someone else has this problem, for me my solution was as follows (I am using sets instead of numbers):
`A = set([1,2,3,4,5])`
`B = set([2,6,7,9])`
`C = set([6,3,9,7,10,2])`
`tmp = A.union(B)`
`totLen = len(tmp.union(C))` 
` venn3([A,B,C], subset_label_formatter=lambda v: f'{v/totLen:.2%}')`
