### ISSUE TITLE
venn3_circles do not align with venn3_unweighted

### ISSUE THREAD

**Issue by asierra-eng** [konstantint/matplotlib-venn#64]
I was trying to align the circles with the unweighted venn diagram for 3 datasets and I couldn't find a way to use the subset_areas=(1, 1, 1, 1, 1, 1, 1) attribute on the venn3_circles method.

![venn3_cirlces do not align with venn3_unweighted](https://user-images.githubusercontent.com/24468648/110515956-f5cad700-80d6-11eb-9520-375c66b8a20e.JPG)

Also, it seems that portion of the venn diagram seems to be cut when I tried to use the venn3_circle method.

![venn3_unweighted without circles](https://user-images.githubusercontent.com/24468648/110516366-7d184a80-80d7-11eb-846d-e730835163f8.JPG)

Thank you very much for your help.

**Comment by konstantint** [comment]
`venn3_circles` does not print numbers, so there is no need to have an analogue of `venn3_unweighted` there. Just call `venn3_circles` with `(1,1,1,1,1,1,1)` as the areas:

```
subsets = [1,2,3,4,5,6,7]
venn3_unweighted(subsets)
venn3_circles((1,1,1,1,1,1,1));
```
