### ISSUE TITLE
Venn diagram from a boolean set notation

### ISSUE THREAD

**Issue by foroda385** [konstantint/matplotlib-venn#68]
This issue extends an already closed issue [#44](https://github.com/konstantint/matplotlib-venn/issues/44).

I took the liberty to create a function based on the code you provided. Below is the code:

```
from matplotlib import pyplot as plt
from matplotlib_venn import venn3, venn3_circles

def list_regions(formula):
    from itertools import product    
    for x in product([False, True], repeat=3):
        if eval(formula, {}, dict(zip('ABC', x))):
            yield ''.join(str(int(x_i)) for x_i in x)

def draw_venn(formula):
    plt.figure(figsize=(6,6))
    v = venn3(subsets=[1]*7,
              set_colors=['white']*3,
              subset_label_formatter=lambda x: '')
    c = venn3_circles(subsets=[1]*7, linestyle='solid')
    for region in list_regions(formula):
        v.get_patch_by_id(region).set_color('black')
    plt.annotate("Ω", (-0.657, 0.557)); plt.axis('on')
    plt.show()
```

It works for almost every formula but produces problems when it comes to complements.

For instance, these work:
```
draw_venn('A and (not B)')
draw_venn('(A or B) and (not C)')
draw_venn('(A and B) and (not C)')
```

However, these don't work:
```
draw_venn('not B')
draw_venn('A or (not B)')
draw_venn('(A and B) or (not C)')
```

The function fails to execute the code with the following exception:

```
Traceback (most recent call last):
  File "/diagrams/venn.py", line 39, in <module>
    draw_venn('not B')
  File "/diagrams/venn.py", line 19, in venn_diagram
    v.get_patch_by_id(region).set_color('black')
  File "/diagrams/venv/lib/python3.8/site-packages/matplotlib_venn/_common.py", line 31, in get_patch_by_id
    return self.patches[self.id2idx[id]]
KeyError: '000'
```

The same error goes for `draw_venn('A or (not B)')` and `draw_venn('(A and B) or (not C)')`

Could you please help me get this code to work?

**Comment by foroda385** [comment]
Actually,  the id `000` corresponds to the universal region Ω.

So, based on your response to the follow up issue [#45](https://github.com/konstantint/matplotlib-venn/issues/45), I edited the function by adding the following:

```
for region in list_regions(formula):
    if region == '000':
        ... # set_(face)color
    else:
        v.get_patch_by_id(region).set_color('black')
```

I am having troubles shading the region Ω. Plus, I cannot find `set_(face)color` in the source code. The [link](https://tiny.cc/sincjz) you provided in the other issue [#45](https://github.com/konstantint/matplotlib-venn/issues/45) is out of date and does no longer exist. So, the only way I found to set the background colour was by passing `facecolor='black'` as a parameter in `plt.figure()`. However, this sets the entire background black and excludes the universal region Ω which still remains white.

Please help!

**Comment by konstantint** [comment]
See if [this](https://colab.research.google.com/drive/1Gz8mBqBL5qMiDu8LqB18Te5uov3e87by?usp=sharing) helps.

Note that matplotlib_venn uses alpha < 1 by default, which does not work as necessary if you decide to color the background. Using alpha=1 and grey color instead of black solves this problem.

**Comment by foroda385** [comment]
Thanks @konstantint, exactly what I was looking for. Works like a charm!
