### ISSUE TITLE
Draft a new release

### ISSUE THREAD

**Issue by firefly-cpp** [konstantint/matplotlib-venn#69]
Hi @konstantint,

Please draft a new release. The last two commits are not packaged in the last release.

**Comment by konstantint** [comment]
Those are just Travis-related fixes that don't really affect the functionality, hence no new version / release.

**Comment by firefly-cpp** [comment]
My motivation is to build a matplotlib-venn package for Fedora (rpm package). I am building from sources where also all tests should be run. Hence, directives in the last two commits are crucial for achieving tasks. For instance, the pytest directive in the latest release is deprecated.

Regardless, there is a chance that I can also produce patches for builds.

**Comment by konstantint** [comment]
Thanks for the clarification. Pushed 0.11.7 to PyPi.
