### ISSUE TITLE
Invalid configuration of circular regions (holes are not supported)

### ISSUE THREAD

**Issue by BrokenSpaghetti02** [konstantint/matplotlib-venn#72]
[](url)The same type of problem was raised back in 2017 and it was not really solved. Here is the issue again:

![Screenshot 2023-06-27 103629](https://github.com/konstantint/matplotlib-venn/assets/67410061/e6cb83cd-239d-484f-8f6e-bfaca1d08152)

Here is the information about the sets I'm using:

rnaseq_60k = {set of 60k genes}
rnaseq_40k = {set of 40k genes}
protein_coding = {set of genes involved in protein coding}

Note: rnaseq_40k is a subset of rnaseq_60k

**Comment by Irfan-Ahmad-byte** [comment]
Did you find the solution? If yes, then kindly share your solution here. Or please share your piece of code.

Thanks,

**Comment by konstantint** [comment]
There is no simple solution apart from inventing a new layout algorithm, which hasn't happened so far :)
There is a workaround, though - you may artificially inflate the intersection area either by temporarily adding the same element to all three sets, or using the `venn3_unweighted` with a tuned value of the `subset_sizes` vector.

**Comment by konstantint** [comment]
Version 1.1.0 (commit b9a34b084a07c361cce9dadd70d580ae8ddf1b34) introduces a new layout algorithm that should be capable of handling some of these corner cases better than the default one.
