### ISSUE TITLE
Missing pure python wheel for Pyodide use ?

### ISSUE THREAD

**Issue by bhugueney** [konstantint/matplotlib-venn#73]
I tried to use matplotlib-venn with [JupyterLite](https://jupyter.org/try-jupyter/lab/) but I ran into a [«Can't find a pure Python 3 wheel for 'matplotlib-venn'»](https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package) .
It seems to me that matplotlib-venn is pure python, so the best solution would be for you to [build the wheel](https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives) if you don't mind.

Thank you very much in advance.

Best Regards.

**Comment by konstantint** [comment]
Sorry for a slow response, somewhy the notification about this issue didn't arrive.

It seems the latest push with twine has published both the source and the wheel distributions (without me doing anything different from what I was previously doing).
