### ISSUE TITLE
An arc length computation test fails with insufficient precision on Travis-CI for Python 3.8

### ISSUE THREAD

**Issue by konstantint** [konstantint/matplotlib-venn#76]
See https://app.travis-ci.com/github/konstantint/matplotlib-venn/jobs/616934442

**Comment by skupr-anaconda** [comment]
Is this issue caused by numpy 1.24 (?) and python 3.8? We got the same error only on `linux-64`, see https://github.com/AnacondaRecipes/matplotlib-venn-feedstock/pull/2#issuecomment-2208334963

**Comment by konstantint** [comment]
I do not have a very good idea of what the real problem here was, but it does seem that different numpy versions on different python versions can produce different types of objects (e.g. sometimes a float, sometimes a np.float. Most confuslingly - sometimes a bool, sometimes a thing like np.True_). I unified some of the code to always return one type in c74216190205c21387c18db7d7ae9e9d1e5469dd.
  
As Travis stopped my builds because of some pricing changes I don't really know whether it would still fail on Travis in some configuration, at least I cannot seem to reproduce any failures on any versions locally.
