### ISSUE TITLE
Improve how layout algorithm handles blank overlaps for 3+ sets

### ISSUE THREAD

**Issue by EarthToMooney** [konstantint/matplotlib-venn#79]
When a third set is added that's a combination of subsets from 2 other sets, it results in an empty section with a label of 0 for the third set:
![image](https://github.com/konstantint/matplotlib-venn/assets/77983993/29efc8f8-8fdd-40d5-8924-864369fcd6a1)If there was an option to remove this empty space, or to add 4 or more sets, it would resolve this issue.

**Comment by konstantint** [comment]
The existence of an empty section is an inevitable consequence of three circles being unable to perfectly represent any combination of 7 area sizes.

You can manually hide it, though:

```
v = venn3(...)
v.get_patch_by_id('001').set_visible(False)
v.get_label_by_id('001').set_visible(False)
```
