### ISSUE TITLE
Order of the labels

### ISSUE THREAD

**Issue by KobaKhit** [konstantint/matplotlib-venn#82]
Hello. Love this project. When using the `venn3` function I found out that this is what the order of the labels is based on the subsets argument in `venn3(subsets=[7,6,5,4,3,2,1])`.

```
a, b, a&b, c, a&c, b&c, a&b&c
7, 6,  5,  4,  3,   2,    1
```

I might have missed it if it is in the documentation. If it is not, I think it will be helpful to include.

**Comment by konstantint** [comment]
Yes, it is mentioned in the documentation in the fifth sentence here: 
![image](https://github.com/user-attachments/assets/d62e71ef-a665-42e2-9504-78a38379b720)

Just in case, note that your notation (a, b, a&b, ...) is not a correct representation of the respective subsets, i.e. (A & not B & not C) != A, etc.
