### ISSUE TITLE
Section missing in the plot

### ISSUE THREAD

**Issue by eafyounian** [konstantint/matplotlib-venn#84]
Hi. I am running the following script using `matplotlib_venn`  version `1.1.1` and I expect to see seven sections. But only six sections are plotted. The missing section has the smallest number, which is `37` (largest is 13727). I also tried different `layout_algorithm`s but this does not change the results. Can you please look into this? 

```py
from matplotlib_venn import venn3
venn3([set(A.index.values), set(B.index.values), set(C.index.values)], # A, B, and C are Pandas data frames
      set_labels=('A', 'B', 'C'),
     );
```

**Comment by konstantint** [comment]
See if the [comment in issue #81](https://github.com/konstantint/matplotlib-venn/issues/81) helps.

**Comment by eafyounian** [comment]
Hi! Thanks so much for your quick reply. Yes, the solution in #81 helped.

Here is my updated, working script:

```py
from matplotlib_venn import venn3
from matplotlib_venn.layout.venn3 import cost_based, DefaultLayoutAlgorithm

ax  = venn3([set(A.index.values), set(B.index.values), set(C.index.values)], # A, B, and C are Pandas data frames
                   set_labels=('A', 'B', 'C'))
plt.close()

sizes = [int(text.get_text()) for text in ax.subset_labels]
mean_size = sum(sizes)/len(sizes)
fraction_increase = 0.15
sizes_adapted = [s + fraction_increase*mean_size for s in sizes]

venn3(sizes, 
      set_labels=('A', 'B', 'C'),
      layout_algorithm = DefaultLayoutAlgorithm(fixed_subset_sizes=sizes_adapted)
     )
```

Finally, thank you for this useful package. :)
